name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: Build binaries
        run: |
          mkdir -p dist
          rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin
          cargo build --release --target x86_64-unknown-linux-gnu
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          cp target/x86_64-unknown-linux-gnu/release/kasetto dist/kasetto-linux-amd64
          cp target/aarch64-unknown-linux-gnu/release/kasetto dist/kasetto-linux-arm64
          cp target/x86_64-apple-darwin/release/kasetto dist/kasetto-darwin-amd64
          cp target/aarch64-apple-darwin/release/kasetto dist/kasetto-darwin-arm64

      - name: Checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: changelog
        with:
          args: --latest --strip header

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.content }}
          files: |
            dist/*
